version: '3'
services:
  node1:
    image: mongo:4.0
    command: "mongod -f /etc/app/node1.conf"
    ports:
      - '27017:27017'
    volumes:
      - ./node1:/etc/app
  node2:
    image: mongo:4.0
    command: "mongod -f /etc/app/node2.conf"
    ports:
      - '27018:27017'
    volumes:
      - ./node2:/etc/app
  node3:
    image: mongo:4.0
    command: "mongod -f /etc/app/node3.conf"
    ports:
      - '27019:27017'
    volumes:
      - ./node3:/etc/app
